config/routes.rb
Rails.application.routes.draw do

  root :to => 'products#main'
  get '/contacts' => 'products#loading'
  get '/about' => 'products#loading'
  get '/price_list' => 'products#loading'
  get '/payment_and_delivery' => 'products#loading'
  get '/installation' => 'products#loading'
  get '/html_popup_editor' => 'products#html_popup_editor'
  get '/view_img_popup' => 'products#view_img_popup'

  resources :custom_pages, except: [:edit, :show]
  post '/custom_pages/set_order' => 'custom_pages#set_order'

  resource :carts, only: [:index] do
    get :edit
    get 'view/:id' => 'carts#view'
    get :statuses
    post :add_position
    delete :remove_position
    post :confirm
    post :proceed
    delete :destroy
    get :zones
    post :add_zone
    delete :del_zone
  end
  get '/carts' => 'carts#index'

  devise_for :users, :controllers => {registrations: 'registrations', passwords: 'passwords'}

  resource :users, :only => [] do
    get 'view/:id' => 'users#show'
    get 'u_login'
    get 'login'
    get 'create'
    get 'confirm_email'
    match 'password_reset', via: [:get, :post]
    get 'email_to_reset_pass'
    get 'is_email_free'
    get 'add_provider'
    match 'account', via: [:get, :post]
  end

  resources :products do
    get :get_images
    post :del_image
  end
  get '/main_content' => 'products#main_content'
  get '/get_category_and_firm_options' => 'products#get_category_and_firm_options'
  post '/create_category_or_firm_option' => 'products#create_category_or_firm_option'
  delete '/delete_category_or_firm_option' => 'products#delete_category_or_firm_option'
  get '/captcha' => 'settings#get_new_captcha'

  resource :settings, :only => [] do
    post :update
    get :global
    get :page_editor
  end

end

app/views/layouts/angular.html.haml
#hide_without_angular
  %script{type: 'text/javascript'}
    if(typeof(angular) == 'undefined')
    {
    //console.log(window.location);
    localStorage.setItem('pathname',window.location.pathname);
    localStorage.setItem('search',window.location.search.slice(1));
    localStorage.setItem('hash',window.location.hash.slice(1));
    window.location.href='/';
    document.getElementById('hide_without_angular').style.display = 'none';
    }
  = yield

app/views/layouts/application.html.haml
%html{'x-ng-app'=>'myapp'}
  %head
    <meta name="fragment" content="!">
    %link{rel: 'shortcut icon', href: image_path('favicon.png')}
    %title{'x-ng-bind'=>'title'}
      ТеплоИнвест
    %meta{name: 'Keywords', content: '{{meta_keywords}}'}
    %meta{name: 'Description', content: '{{meta_description}}'}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application.js', 'data-turbolinks-track' => true
    %script{src: 'http://api-maps.yandex.ru/2.1/?lang=ru_RU&mode=debug&coordorder=longlat', type: 'text/javascript'}
    = csrf_meta_tags
  %body{'x-ng-controller'=>'MainController'}
    #glob{style: 'position: absolute; top: 0px;'}
    .global{'x-ng-show'=>'loadFinishedCompletly'}
      .head_wraper
        %div.head_img_keeper
          %img.header_sb{src: image_path('header_side_bar.jpg')}
        .head_sub_wrapper
          %div{style: 'text-align: right; vertical-align: middle;'}
            %table.login
              %tr{'x-ng-show'=>'userRequestComplete'}
                %td.new_user_td{'x-ng-hide'=>'currentUser'}
                  = link_to 'Вход / Регистрация', login_users_path
                %td{'x-ng-show'=>'currentUser && !currentUser.is_admin'}
                  = link_to 'Настройки', account_users_path
                %td{'x-ng-show'=>'currentUser && currentUser.is_admin'}
                  = link_to 'Настройки', global_settings_path
                %td{'x-ng-show'=>'currentUser && currentUser.is_admin'}
                  Необработанных заказов:
                  %b
                    {{pendingCount}}
                %td{'x-ng-hide'=>'currentUser'}
                  Войти через
                %td{style: 'min-width: 84px; padding-right: 0;', 'x-ng-hide'=>'currentUser'}
                  %div#uLogin{'data-ulogin'=>"display=panel;fields=first_name,last_name;providers=vkontakte;hidden=other;redirect_uri=;callback=uLoginOauth"}
                %td.user_info{'x-ng-show'=>'currentUser'}
                  {{currentUser.email}}
                %td{'x-ng-show'=>'currentUser', style: 'padding-right: 14px;'}
                  %a{'x-ng-click'=>'logout()'}
                    Выйти
          %table.head_panel
            %tbody
              %tr
                %td
                  .tdBox
                    = link_to '<div class="head_spacer"><span>Главная</span></div>'.html_safe, root_path
                %td
                  .tdBox
                    = link_to '<div class="head_spacer"><span>Все Товары</span></div>'.html_safe, products_path
                %td
                  .tdBox
                    = link_to '<div class="head_spacer"><span>Контакты</span></div>'.html_safe, '/contacts'
                %td
                  .tdBox
                    = link_to '<div class="head_spacer"><span>О нас</span></div>'.html_safe, '/about'
                %td
                  .tdBox
                    = link_to '<div class="head_spacer"><span>Прайс-листы</span></div>'.html_safe, '/price_list'
                %td
                  .tdBox
                    = link_to '<div class="head_spacer"><span>Оплата и доставка</span></div>'.html_safe, '/payment_and_delivery'
                %td
                  .tdBox
                    = link_to '<div class="head_spacer"><span>Монтаж</span></div>'.html_safe, '/installation'
                %td{'x-ng-class'=>'{full_cart_bg: cartNotEmpty}', 'x-ng-hide'=>'currentUser.is_admin'}
                  .tdBox
                    = link_to '<div class="head_spacer"><span>Корзина</span></div>'.html_safe, '', 'x-ng-click'=>'goToViewCartPage()'
                %td{'x-ng-class'=>'{full_cart_bg: anyNesOrders}', 'x-ng-show'=>'currentUser.is_admin'}
                  .tdBox
                    = link_to '<div class="head_spacer"><span>Заказы</span></div>'.html_safe, '/carts'


      %div.content
        %table.content
          %tbody
            %tr
              %td.assortment{'x-ng-hide'=>'form_displayed'}

                .new_menu_style
                  .cats_block{'x-ng-repeat'=>'cat in cats_list | orderBy:\'name\'', class: 'cat_{{cat.id}}'}
                    %a.cat_link{'x-ng-href'=>products_path+'?category={{cat.id}}'}
                      %h4
                        {{cat.name}}
                    .slider
                      .sub_cats_block{'x-ng-repeat'=>'sub_cat in cat.sub_cats | orderBy:\'name\'', class: 'sub_cat_{{sub_cat.id}}'}
                        %a{'x-ng-href'=>products_path+'?category={{cat.id}}&sub_cat={{sub_cat.id}}'}
                          %h5
                            {{sub_cat.name}}
                        .sub_slider
                          %ul.alt_firms_block
                            %li{'x-ng-repeat'=>'firm in sub_cat.firms | orderBy:\'name\'', class: 'firm_{{firm.id}}'}
                              %a{'x-ng-href'=>products_path+'?sub_cat={{sub_cat.id}}&firm={{firm.id}}&category={{cat.id}}'}
                                {{firm.name}}
                      %ul.alt_firms_block
                        %li{'x-ng-repeat'=>'firm in cat.firms | orderBy:\'name\'', class: 'firm_{{firm.id}}'}
                          %a{'x-ng-href'=>products_path+'?firm={{firm.id}}&category={{cat.id}}'}
                            {{firm.name}}

              %td
                .main{'ng-view'=>''}
                  = yield
      .downside
        =# footer...

app/views/layouts/mail.html.haml
<!DOCTYPE HTML>
%html
  %head
    %meta{'http-equiv'=>'Content-Type', 'content'=>'text/html; charset="UTF-8"'}
    = stylesheet_link_tag 'mail.css.scss', media: 'all'
  %body
    = yield